name: Create GitHub Release

on:
  push:
    paths:
      - 'version.txt'

jobs:
  create_github_release:
    runs-on: ubuntu-latest
    name: Foundry Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: GitHub Release Release
        id: github-release
        uses: foundryvtt-dcc/foundry-release-action@main
        with:
          actionToken: ${{ secrets.GITHUB_TOKEN }}
          manifestFileName: 'system.json'
