name: Update Foundry Manifest Post-Release

on:
  release:
    types:
      - published

jobs:
  update_manifest_post_release:
    runs-on: ubuntu-latest
    name: Update Foundry Manifest Post-Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main

      - name: Update Foundry Manifest Post-Release
        id: foundry-manifest-update
        uses: foundryvtt-dcc/foundry-manifest-update-action@main
        with:
          actionToken: ${{ secrets.GITHUB_TOKEN }}
          manifestFileName: 'system.json'
